### ISSUE TITLE
Tips on creating Blender AMI image like yours?

### ISSUE THREAD

**Issue by sundriftproductions** [rider-rebooted/win_brenda_console#4]
Sorry to post this here, as I don't know how else to get in touch with you since brendapro.com is down. I'm looking to create my own custom AMI image. I looked at your  ami-33a4ad59 image and, from what I can tell, it appears that it's a Windows image. Do you have any tips or can you point me toward any instructions as far as setting up a custom AMI image like yours, but with Blender installed -- so that it can be accessed by Brenda?

Thank you!

**Comment by TenseFX** [comment]
Hi Simple Carnival,

My image was installed on Ubuntu. I can take a closer look at the weekend as I think I made notes somewhere. Have you had a look for others? I assume you're looking to install the latest version of Blender on one? There might be a way you could clone that one and update the version that's already on there.

Regards

Andy

**Comment by TenseFX** [comment]
I've just messaged Todd and he said Brenda Pro should be back up next week.

**Comment by sundriftproductions** [comment]
Hi Andy --

Thanks for your response. I had assumed it was a Windows image because Brenda UI says "win_brenda" and the EC2 control panel said the platform was "Other Linux".  That's helpful to know that it's a Ubuntu image instead.

I'm looking to make my own AMI because I want to figure out how to handle a project with lots of image sequence files (~10 GB), as well as projects with pre-computed fluid simulation files (~3GB). I'm thinking of uploading all of those files to a personal AMI and then figure out how to make the Blender project file recognize those files. As far as the version of Blender I'm looking to use, I'm planning to use the next release (2.78b? It should have pretty significantly improved Cycles rendering performance), though I'm fine with experimenting with 2.78a as I get the hang of working with AMIs. 

I've been researching and experimenting with EC2 stuff (and have had some success with Brenda UI a few months ago), but I'm at a loss as far as what I need to do to set up an AMI to work with Brenda. Any advice you can provide would be greatly appreciated!

-Jeff

**Comment by sundriftproductions** [comment]
Actually, never mind...I found instructions on how to set up an AMI in Brenda's readme.md file. Going to give it a shot!

**Comment by TenseFX** [comment]
Hi Simple Carnival,

Apologies for not getting back to you sooner, it's been a busy few weeks. i see BrendaPro isn't up yet. I have just looked for instructions on my computer for creating one but unfortunately it's all on the BrendaPro site! How is it going?

**Comment by sundriftproductions** [comment]
I was able to create an AMI and install the necessary software. I made it so that only my IP address could access the image. Unfortunately, I ran into problems when I tried assigning the AMI in the Brenda front end app -- the app just froze. I ran out of time and wasn't able to investigate further. I suspect there might be some sort of issue where the Brenda front end was expecting a public AMI and I picked an AMI which...I'm not sure if it was technically considered public. I should have time to look into it this coming week.

**Comment by TenseFX** [comment]
If by the front end you mean my win_brenda_console then all that does is change the value in the "ami.py" file in the "C:\brenda-master\brenda" folder to whatever you type. It's not doing anything smart like checking if it exists or if it's public. 
The problem could be on the Amazon side of things...or your IP could have changed if you don't have a static IP address.

**Comment by TenseFX** [comment]
Hi,

Todd has told me that the hosting company have lost the back up to the Brendapro site and he's trying to find a way to recreate it again possibly with the Way Back Machine (archive.org). There's a cache of Brendapro there and Google has a cache too.

Btw I'm working on re-writing win_brenda with a gui at the moment which should be cool

**Comment by sundriftproductions** [comment]
Thanks for the update, Andy. I haven't had time to experiment with Brenda lately, as I'm wrapping up a couple of Blender-related projects. Keep me informed of any Brenda updates, though!

-Jeff

**Comment by sundriftproductions** [comment]
OK, I'm now back on this and plan to be using Brenda a lot. I posted this on your AWS forum, but I'm posting it here in case you don't see it.

I've been able to run Win-Brenda using the existing recommended AMIs. Now I'm trying to set up my own AMI with the newest version of Blender (2.78c) and I think I'm missing something. Long story short: when I run an instance of the custom AMI via Win-Brenda, nothing gets rendered. I don't know how to view what's going on in my particular AMI because I get nothing from the "Tail log from instances" feature. The AMI is shown to be running in the AWS console -- I just think I don't have something set up correctly.

Here are the steps I take to create my AMI:

1) Go to the EC2 console and click on launch instance. On the left you will see AMI options. Quickstart is highlighted by default. Click on Community AMIs. From the checkboxes on the left, choose Ubuntu, 64-bit, and EBS. Enter "Yakkety Yak" for the search term. ("Yakkety Yak" is the code name for Ubuntu 16.10.) Pick an AMI with Virtualization type: HVM (not paravirtual). I picked this image: "ubuntu/images-testing/hvm-ssd/ubuntu-yakkety-daily-amd64-server-20170716 - ami-01212b17"
2) Choose an Instance Type: I picked "c3.large"
3) Configure Instance Details: I left all the defaults. FYI -- Shutdown Behavior is set to "Stop".
4) Add Storage: Leave all the defaults (8 GB for the root).
5) Add Tags: I left the default options.
6) Configure Security Groups: For now, I'm going with the defaults:
	- Assign a Security Group: Create a NEW security group
	- Type: SSH, Source: Anywhere
7) Select an existing key pair or create a new key pair: I chose an existing key pair that I know that works.
8) If you created a new key in step 7, generate the proper key here: http://blog.powercram.com/2009/07/connecting-to-aws-ec2-instance-linux.html 
9) After you launch the PuTTY command line, you'll see the command line say "login as:". Put in "ubuntu" (sans quotes).
10) Now run this: 
	sudo perl -p -i.bak -e 's/^disable_root: 1/disable_root: 0/' /etc/cloud/cloud.cfg
	sudo perl -p -i.bak -e 's/.*ssh-rsa/ssh-rsa/' /root/.ssh/authorized_keys
	sudo add-apt-repository -y ppa:irie/blender
	sudo apt-get update
	sudo apt install blender
	sudo apt-get install -y blender python-pip gcc python-dev libcurl4-openssl-dev git unzip
	sudo apt-get install python-pip
	sudo pip install -U boto
	sudo pip install -U s3cmd
	sudo apt-get install git
	sudo apt-get  update; sudo apt-get install  python-dev -y
	sudo apt-get install libcurl4-openssl-dev

11) Next, download and install Brenda:
	git clone http://github.com/jamesyonan/brenda.git
	cd brenda
	sudo python setup.py install

12) At this point, you still don't have the latest version of Blender. To do that...
	sudo add-apt-repository ppa:thomas-schiex/blender
	sudo apt update
	sudo apt install blender

13) To check which version of Blender you have installed:
	blender -v

I've used Linux a bit, but I do not consider myself an expert. Any ideas on things that I can check to make sure that this image runs correctly?

**Comment by sundriftproductions** [comment]
Never mind -- I got it working. I found a detailed set of instructions here: https://github.com/robksawyer/brenda-web/wiki/How-to-Create-an-Amazon-Machine-Image-(AMI)
